# Number of ticks to sleep a player sleep before making it day
napTime: 100

# The worlds that this plugin should listen for sleepers.
# Note that each world is handled separately.  Sleeping off
# night in a particular world will not affect other worlds
# listed here.
worlds:
  - world

messages:
  sleep_warning: '§b%player_name% is sleeping.'
  woken_up: '§b%player_name% woke you up!'
  night_skipped: '§bNight was skipped!'
  click_here: '  §9Click here to wake up the sleeper(s)'
  wake_them_up: 'Wake them up'