# Number of ticks to sleep a player sleep before making it day
napTime: 100

# The worlds that this plugin should listen for sleepers.
# Note that each world is handled separately.  Sleeping off
# night in a particular world will not affect other worlds
# listed here.
worlds:
  - world